nelmio_api_doc:
    documentation:
        info:
            title: "Vehicle API"
            description: "API documentation for managing vehicles"
            version: "1.0.0"
    areas:
        default:
            path_patterns: ['^/api']
