version: '3.8'

services:
  php:
    image: php:8.1-fpm
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
