# config/services.yaml
parameters:
    locale: 'en'

services:
    # Domyślna konfiguracja autowiring i autokonfiguracja
    _defaults:
        autowire: true      # Automatyczne wstrzykiwanie zależności
        autoconfigure: true # Automatyczna konfiguracja (np. oznaczanie kontrolerów)

    # Rejestracja kontrolerów jako serwisy
    App\Module\:
        resource: '../src/Module/*'
        exclude: '../src/Module/*/Entity' # Wykluczenie encji, jeśli takie istnieją
        tags: 
          - 'controller.service_arguments' # Automatyczne oznaczenie kontrolerów
          - 'doctrine.repository_service'  # Automatyczne oznaczenie repozytoriów

